# Site settings
title: Gourav Shenoy’s Blog
email: goshenoy@indiana.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a Research Asssistant at the <a href="https://sgrc.iu.edu/" target="_blank">Science Gateway Research Center</a> at Indiana University. A results-driven, customer-focused, articulate and analytic Software Engineer who can think “out of the box”. Strong in design, integration and implementing. Expert in Java/J2EE, OpenStack cloud technology, PaaS platform such as IBM BlueMix and public clouds such as IBM SoftLayer, Amazon EC2, & Numergy; along with database analysis and design. Skilled in developing high quality code and architectural systems research. Strong written and verbal communications. Interested in a challenging technical track career in an application development or research environment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: “https://gouravshenoy.github.io” # the base hostname & protocol for your site
twitter_username: GouravShenoy
github_username:  gouravshenoy
facebook_username:  gourav.shenoy
linkedin_username:  in/gouravshenoy
insta_username:	    gourav_shenoy

# Build settings
markdown: kramdown

paginate: 4

author: Gourav Shenoy

gems: [jekyll-paginate]
